randomString: testme.c
	gcc -o randomString -g testme.c

randomStringTestResults.out: randomString
	echo "results for random string testing" > randomStringTestResults.out
	./randomString >> randomStringTestResults.out
